language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - pip install mock==1.0
  - pip install coverage
  - pip install nose
  - pip install -U setuptools
script:
  - pip install .
  - nosetests --with-coverage --cover-package=beastling --with-doctest beastling
before_install:
  pip install codecov
after_success:
  codecov

